### ISSUE TITLE
Compiler pass to insert code to output all memory accesses (along with thread/CPU ID and timestamp)

### ISSUE THREAD

**Issue by dhoekwater** [thomasebsmith/eecs583-f21-group21#2]
- [x] (Task 1) Whenever we encounter a load or store instruction, write it to a file (thread id / CPU core, timestamp/seq id, memory address, load vs. store)
- [x] (Task 2) Do we also need to have a way to map address -> location in code?

**Comment by dhoekwater** [comment]
Finished Task 1 with [`pinatrace.cpp`](https://github.com/thomasebsmith/eecs583-f21-group21/blob/master/pin/pinatrace.cpp)

**Comment by thomasebsmith** [comment]
Finished Task 2 (for global variables) with [`globals.cpp`](https://github.com/thomasebsmith/eecs583-f21-group21/blob/master/src/globals/globals.cpp).
