### ISSUE TITLE
Write a 3-5 page report

### ISSUE THREAD

**Issue by dhoekwater** [thomasebsmith/eecs583-f21-group21#7]
Turn in our project report at 5pm on Dec 16.
- [x] Set up an overleaf document
    - [x] Create a document in IEEE format
    - [x] Share with everyone
- [x] Abstract
- [x] Introduction
- [x] Related Work
- [x] Design & Implementation
- [x] Evaluation
- [x] Conclusion
- [x] References (autogenerated)

**Comment by tonyb7** [comment]
Link to view: https://www.overleaf.com/read/jftzczrxsypz
Link to edit in Slack
